### PR TITLE
add more render support

### LINKED ISSUE #1: privacy
It should be clear in the readme that data is going to be sent to https://www.plantuml.com if you use this plugin. It's be good if there was an option to use your own server if you have one.

### PR DESCRIPTION
**Pull request by miao1007**
1. local rendering
2. self-hosted sever support(fixed #1)

### CODE REVIEW

**Comment by wafer-li** [comment]
Thanks!

But this PR has too much breaking changes, and I don't have much time to manage this repo.

I am considering to transfer this repo to you, what do you think?

**Comment by miao1007** [comment]
thanks, that's better, I have a solution for better PlantUML provision.Best Wishes--------原始郵件 --------主旨：Re: [wafer-li/hexo-filter-plantuml] add more render support (#3)寄件者：Wafer Li 收件者：wafer-li/hexo-filter-plantuml 副本：Haruhi ,Author Thanks!
But this PR has too much breaking changes, and I don't have much time to manage this repo.
I am considering to transfer this repo to you, what do you think?

**Comment by wafer-li** [comment]
Because you are forking this repo, and have it in your account.

Therefore I could not transfer ownership of this repo to you.

I will merge this PR, and when you delete your fork, please notify me and I will transfer this immediately

**Comment by miao1007** [comment]
That's ok, you can trans to me now.

**Comment by wafer-li** [comment]
@miao1007
Transfer requested.

**Comment by wafer-li** [comment]
And I could transfer npm package to you, if you could provide your npm account

**Comment by miao1007** [comment]
Hi, my account is miao1007 too, and package trans is welcomed.

**Comment by wafer-li** [comment]
Done.
Now you should own total control of this repo and npm package

image

**Pull request merged**
